### ISSUE TITLE
Error al intentar cargar el proyecto

### ISSUE THREAD

**Issue by Iv4mn** [ronystico/my-first-csharp#1]
Al intentar cargar cualquier proyecto desde Mono-Develop, me tiran los siguientes errores:

**Calculadora operaciones básicas**:
`Error al intentar cargar el proyecto '/home/ivan/Documentos/git/my-first-csharp/Calculadoraoperacionesbasicas/SticoSumResMulDivDeDosNumeros/Calculadoraoperacionesbasicas.csproj': Archivo no encontrado: /home/ivan/Documentos/git/my-first-csharp/Calculadoraoperacionesbasicas/SticoSumResMulDivDeDosNumeros/Calculadoraoperacionesbasicas.csproj`

**Datos inversos**:

`Error al intentar cargar el proyecto '/home/ivan/Documentos/git/my-first-csharp/Calculadoraoperacionesbasicas/SticoSumResMulDivDeDosNumeros/Calculadoraoperacionesbasicas.csproj': Archivo no encontrado: /home/ivan/Documentos/git/my-first-csharp/Calculadoraoperacionesbasicas/SticoSumResMulDivDeDosNumeros/Calculadoraoperacionesbasicas.csproj`

**Cuál número es menor**:

`Error al intentar cargar el proyecto '/home/ivan/Documentos/git/my-first-csharp/Calculadoraoperacionesbasicas/SticoSumResMulDivDeDosNumeros/Calculadoraoperacionesbasicas.csproj': Archivo no encontrado: /home/ivan/Documentos/git/my-first-csharp/Calculadoraoperacionesbasicas/SticoSumResMulDivDeDosNumeros/Calculadoraoperacionesbasicas.csproj`

**Comment by ronystico** [comment]
El commit 09788200d1e2d457aa1b617533c7e3f4359661dc debería resolver el problema. Por favor verifica que es así

**Comment by Iv4mn** [comment]
Ahora no da error pero el programa no inicia, solo consigo la siguiente salida:
```
Loaded assembly: /home/ivan/Downloads/my-first-csharp/Cualnumeroesmenor/Cualnumeroesmenor/bin/Debug/Cualnumeroesmenor.exe
Ingrese el primer numero

Ingrese el segundo numero

Ingrese el tercer numero


El numero 0 es menor


```
